import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/app-sidebar"

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" className={cn("font-sans", geist.variable)}
    >
      <body className="min-h-screen overflow-hidden bg-[#0b0f14] text-[#f5f1ea]">
        <Sidebar />
        <main className="h-screen overflow-y-auto bg-transparent md:pl-60">
          {children}
        </main>
      </body>
    </html>
  );
}
